sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: CBLbrS5PrTlHkTZ1sAkIl5KOUSeadw/9PKG2pYCX8/2APS/JGv9bU7JckdWW2vYk4UdRCYUxvZROY4UWac2a1PlKrPnHGI3jUWv1QFd80FlQJ+e0kXMtbTFloft1pjx/KxDjUW8FeKykCHQwOujc58Q2t5AmnfFqj1JWlPZ3pdV/1/evGfvqVzLBS94MaucKAa3hLGMi58A045iOeOnEio7s1Lt7SglRDTgsUQHHe53Eqw2Y7uoMaWRVeHac+LanuvI7YTHN4Rfc3FZcEEhhA4j59zUL4IWJhuE+Ydpo8hyGk78ea6/WFQzkHZjcoHtosAVvBBj0dT74P+cZ/zSQiAu3ABzEXa1saH/CFJVtxFw0mQUQsi1ySNJDQGDYB1/rywgXBabXe9KhF25C8ozc18r+EYF/0248TNHhoDP/+SA5Ikmxwtl01NSEz9zqtFNg5K46yvL/v45mKBlHneuIP+inSn5mYmedmSDHgLILqGxhI5C+0EAYQwpfKwbGLthM+ogd+a3Qwhff3+cgNl2G2cVUYV+aLKll98yVm7swTsqGQVjLI5nNPevDkcNruUKq2FwnhnGvRiBGzO5kpN23FHDhpdgF7OPbk+VfFEm8l0ce+gt6oUW4nXdaSZbvn1X8mZJDgHdoMyB+louZL5skye0VHRzsKT76WaS5dd68lDw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Diary-of-Samuel-Pepys---Volume-64--April-1668_4188
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy